import { CrdExtractError, unsafeCoerce } from "@konfig.ts/core";
import { Data, Effect, Schema } from "effect";
import { FileSystem } from "effect/FileSystem";
import { Path } from "effect/Path";
import { ChildProcess, ChildProcessSpawner } from "../_unstable";
import { compile } from "json-schema-to-typescript";
import * as YAML from "yaml";

export const GENERATED_HEADER = "// Generated by @konfig.ts/cli — do not edit by hand";

const _CHART_NAME_PATTERN = /^[a-zA-Z0-9][a-zA-Z0-9._-]*$/;
const _CHART_VERSION_PATTERN = /^[a-zA-Z0-9][a-zA-Z0-9._+-]*$/;
const _CHART_REPO_PATTERN = /^(https?|oci):\/\/[A-Za-z0-9._~:/?#\[\]@!$&'()*+,;=%-]+$/;
const _ID_PATTERN = /^[a-zA-Z0-9][a-zA-Z0-9._-]*$/;

const ChartName = Schema.String.check(
	Schema.isPattern(_CHART_NAME_PATTERN, {
		description: "Helm chart name (alphanumeric, dot, underscore, dash)",
	}),
);

const ChartVersion = Schema.String.check(
	Schema.isPattern(_CHART_VERSION_PATTERN, {
		description: "Helm chart version (semver-compatible)",
	}),
);

const ChartRepoUrl = Schema.String.check(
	Schema.isPattern(_CHART_REPO_PATTERN, {
		description: "Helm chart repo URL (http(s)/oci scheme, no shell metachars)",
	}),
);

const ChartId = Schema.String.check(
	Schema.isPattern(_ID_PATTERN, {
		description: "Chart release id (alphanumeric, dot, underscore, dash)",
	}),
);

export const CrdExtractOptionsSchema = Schema.Struct({
	repo: ChartRepoUrl,
	chart: ChartName,
	version: ChartVersion,
	id: ChartId,
	outDir: Schema.String,
	cacheDir: Schema.String,
});

export interface CrdExtractOptions {
	readonly repo: string;
	readonly chart: string;
	readonly version: string;
	readonly id: string;
	readonly outDir: string;
	readonly cacheDir: string;
}

export class CrdInputDecodeError extends Data.TaggedError("CrdInputDecodeError")<{
	readonly cause: unknown;
}> {
	get message(): string {
		return `CRD extract inputs rejected by schema (untrusted shell args refused): ${String(this.cause)}`;
	}
}

const _decodeOpts = (opts: CrdExtractOptions) =>
	Schema.decodeUnknownEffect(CrdExtractOptionsSchema)(opts).pipe(
		Effect.mapError((cause) => new CrdInputDecodeError({ cause })),
	);

interface CrdDocument {
	readonly crdName: string;
	readonly group: string;
	readonly schema: Record<string, unknown>;
	readonly versions: readonly string[];
}

const _parseCrdDocs = (yamlText: string): CrdDocument[] => {
	const docs: unknown[] = [];
	for (const chunk of yamlText.split(/^---\s*$/m)) {
		const trimmed = chunk.trim();
		if (!trimmed) continue;
		try {
			const parsed = YAML.parse(trimmed);
			if (parsed && typeof parsed === "object") docs.push(parsed);
		} catch {
			// Skip unparseable chunks
		}
	}

	const crds: CrdDocument[] = [];
	const reason = "raw parsed YAML — every read is validated by an explicit kind/typeof check";
	for (const doc of docs) {
		const d = unsafeCoerce<Record<string, unknown>>(doc, reason);
		if (d.kind !== "CustomResourceDefinition") continue;
		const meta = unsafeCoerce<Record<string, unknown> | undefined>(d.metadata, reason);
		const spec = unsafeCoerce<Record<string, unknown> | undefined>(d.spec, reason);
		if (!meta || !spec) continue;

		const crdName = String(meta.name ?? "");
		if (!crdName) continue;

		const group = String(spec.group ?? "");
		const versions = unsafeCoerce<Array<Record<string, unknown>> | undefined>(spec.versions, reason);
		if (!versions?.length) continue;

		const versionNames: string[] = [];
		let schema: Record<string, unknown> | undefined;

		for (const v of versions) {
			const vName = String(v.name ?? "");
			if (vName) versionNames.push(vName);
			if (!schema) {
				const validation = unsafeCoerce<Record<string, unknown> | undefined>(v.schema, reason);
				const openAPI = unsafeCoerce<Record<string, unknown> | undefined>(validation?.openAPIV3Schema, reason);
				if (openAPI) schema = openAPI;
			}
		}

		if (!schema) {
			schema = { type: "object", additionalProperties: true };
		}

		crds.push({ crdName, group, schema, versions: versionNames });
	}
	return crds;
};

const _crdNameToIdentifier = (crdName: string): string => {
	const resource = crdName.split(".")[0] ?? crdName;
	return resource
		.split(/[-_]/)
		.map((s) => `${s.charAt(0).toUpperCase()}${s.slice(1)}`)
		.join("");
};

const _generateCrdTs = (crd: CrdDocument) =>
	Effect.tryPromise(async () => {
		const identifier = _crdNameToIdentifier(crd.crdName);
		const inputType = `${identifier}Input`;

		let compiledTypes: string;
		try {
			compiledTypes = await compile(unsafeCoerce<Parameters<typeof compile>[0]>(crd.schema, "json-schema-to-typescript's input type is structurally a JSON Schema object"), inputType, {
				bannerComment: "",
				additionalProperties: false,
				enableConstEnums: false,
				strictIndexSignatures: false,
			});
		} catch {
			compiledTypes = `export type ${inputType} = Record<string, unknown>;\n`;
		}

		return [
			compiledTypes,
			`// CRD: ${crd.crdName} (group: ${crd.group}, versions: ${crd.versions.join(", ")})`,
			`// Use Manifest.make from @konfig.ts/core to produce a RawYaml resource at render time.`,
		].join("\n");
	});

interface _PullChartInput {
	readonly opts: CrdExtractOptions;
	readonly cachedTgz: string;
}

const _pullChart = (input: _PullChartInput) =>
	Effect.gen(function* () {
		const fs = yield* FileSystem;
		const spawner = yield* ChildProcessSpawner;

		yield* fs.makeDirectory(input.opts.cacheDir, { recursive: true });
		const exists = yield* fs.exists(input.cachedTgz);
		if (exists) return;

		const cmd = ChildProcess.make("helm", [
			"pull",
			"--repo",
			input.opts.repo,
			input.opts.chart,
			"--version",
			input.opts.version,
			"--destination",
			input.opts.cacheDir,
		]);
		yield* spawner.exitCode(cmd);
	});

export const extractCrdsEffect = (opts: CrdExtractOptions) =>
	Effect.gen(function* () {
		const decoded = yield* _decodeOpts(opts);
		const fs = yield* FileSystem;
		const path = yield* Path;
		const spawner = yield* ChildProcessSpawner;

		const tmpDir = yield* fs.makeTempDirectoryScoped({ prefix: "konfig-crd-" });

		const untarCmd = ChildProcess.make("helm", [
			"pull",
			"--repo",
			decoded.repo,
			decoded.chart,
			"--version",
			decoded.version,
			"--untar",
			"--destination",
			tmpDir,
		]);
		yield* spawner.exitCode(untarCmd);

		const chartDir = path.join(tmpDir, decoded.chart);
		const crdsDir = path.join(chartDir, "crds");

		const allYaml: string[] = [];

		const crdsExists = yield* fs.exists(crdsDir);
		if (crdsExists) {
			const crdFiles = yield* fs.readDirectory(crdsDir);
			for (const f of crdFiles.filter(
				(n) => n.endsWith(".yaml") || n.endsWith(".yml"),
			)) {
				const content = yield* fs.readFileString(path.join(crdsDir, f));
				allYaml.push(content);
			}
		}

		const cachedTgz = path.join(
			decoded.cacheDir,
			`${decoded.chart}-${decoded.version}.tgz`,
		);
		yield* _pullChart({ opts: decoded, cachedTgz });

		const templateCmd = ChildProcess.make("helm", [
			"template",
			decoded.chart,
			cachedTgz,
			"--include-crds",
			"--no-hooks",
		]);
		const templateOut = yield* spawner.string(templateCmd);
		allYaml.push(templateOut);

		const seen = new Map<string, CrdDocument>();
		for (const yaml of allYaml) {
			for (const crd of _parseCrdDocs(yaml)) {
				if (!seen.has(crd.crdName)) seen.set(crd.crdName, crd);
			}
		}

		if (seen.size === 0) {
			yield* fs.makeDirectory(decoded.outDir, { recursive: true });
			const stubPath = path.join(decoded.outDir, `${decoded.id}.ts`);
			yield* fs.writeFileString(
				stubPath,
				`${GENERATED_HEADER}\n// No CRDs found in chart ${decoded.chart}@${decoded.version}\nexport {};\n`,
			);
			return;
		}

		const parts: string[] = [GENERATED_HEADER, ""];
		for (const crd of seen.values()) {
			const ts = yield* _generateCrdTs(crd);
			parts.push(ts, "");
		}

		yield* fs.makeDirectory(decoded.outDir, { recursive: true });
		const outPath = path.join(decoded.outDir, `${decoded.id}.ts`);
		yield* fs.writeFileString(outPath, parts.join("\n"));
	}).pipe(
		Effect.scoped,
		Effect.mapError((cause) => {
			if (cause instanceof CrdInputDecodeError) return cause;
			return new CrdExtractError({ chart: opts.chart, cause });
		}),
	);

export interface VerifyCrdsInput {
	readonly releases: readonly CrdExtractOptions[];
	readonly committedDir: string;
}

export const verifyCrdsEffect = (input: VerifyCrdsInput) =>
	Effect.gen(function* () {
		const fs = yield* FileSystem;
		const path = yield* Path;

		const tmpDir = yield* fs.makeTempDirectoryScoped({ prefix: "konfig-verify-" });
		const drifted: string[] = [];
		for (const release of input.releases) {
			yield* extractCrdsEffect({ ...release, outDir: tmpDir });
			const tmpFile = path.join(tmpDir, `${release.id}.ts`);
			const committedFile = path.join(input.committedDir, `${release.id}.ts`);

			const tmpContent = yield* fs.readFileString(tmpFile).pipe(Effect.orElseSucceed(() => ""));
			const committedContent = yield* fs
				.readFileString(committedFile)
				.pipe(Effect.orElseSucceed(() => ""));

			if (!committedContent.startsWith(GENERATED_HEADER)) {
				drifted.push(`${release.id}.ts (missing generated header)`);
				continue;
			}

			if (tmpContent !== committedContent) {
				drifted.push(`${release.id}.ts`);
			}
		}
		return drifted;
	}).pipe(Effect.scoped);
