// Generated by @konfig.ts/cli — CRD extraction pipeline.
// Runs helm pull + helm template --include-crds, deduplicates by metadata.name,
// parses openAPIV3Schema, runs json-schema-to-typescript, and writes output.

import { exec as execCb } from "node:child_process";
import * as fs from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";
import { promisify } from "node:util";
import { compile } from "json-schema-to-typescript";
import * as YAML from "yaml";

const exec = promisify(execCb);

export const GENERATED_HEADER = "// Generated by @konfig.ts/cli — do not edit by hand";

export interface CrdExtractOptions {
	/** Helm repo URL */
	readonly repo: string;
	/** Chart name */
	readonly chart: string;
	/** Pinned version */
	readonly version: string;
	/** Chart identifier used for the output filename (e.g. "sops-secrets-operator") */
	readonly id: string;
	/** Directory to write generated TS file */
	readonly outDir: string;
	/** Directory used to cache chart tarballs (from konfig.json helm.cacheDir) */
	readonly cacheDir: string;
}

interface CrdDocument {
	readonly crdName: string;
	readonly group: string;
	readonly schema: Record<string, unknown>;
	readonly versions: readonly string[];
}

// Parse CRD documents from raw YAML text (multi-doc or single-doc).
const parseCrdDocs = (yamlText: string): CrdDocument[] => {
	const docs: unknown[] = [];
	for (const chunk of yamlText.split(/^---\s*$/m)) {
		const trimmed = chunk.trim();
		if (!trimmed) continue;
		try {
			const parsed = YAML.parse(trimmed);
			if (parsed && typeof parsed === "object") docs.push(parsed);
		} catch {
			// Skip unparseable chunks
		}
	}

	const crds: CrdDocument[] = [];
	for (const doc of docs) {
		const d = doc as Record<string, unknown>;
		if (d.kind !== "CustomResourceDefinition") continue;
		const meta = d.metadata as Record<string, unknown> | undefined;
		const spec = d.spec as Record<string, unknown> | undefined;
		if (!meta || !spec) continue;

		const crdName = String(meta.name ?? "");
		if (!crdName) continue;

		const group = String(spec.group ?? "");
		const versions = spec.versions as Array<Record<string, unknown>> | undefined;
		if (!versions?.length) continue;

		// Collect per-version schemas; prefer the first version that has one.
		const versionNames: string[] = [];
		let schema: Record<string, unknown> | undefined;

		for (const v of versions) {
			const vName = String(v.name ?? "");
			if (vName) versionNames.push(vName);
			if (!schema) {
				const validation = v.schema as Record<string, unknown> | undefined;
				const openAPI = validation?.openAPIV3Schema as Record<string, unknown> | undefined;
				if (openAPI) schema = openAPI;
			}
		}

		if (!schema) {
			// No schema found — use a permissive object schema
			schema = { type: "object", additionalProperties: true };
		}

		crds.push({ crdName, group, schema, versions: versionNames });
	}
	return crds;
};

// Convert a CRD name like "clusters.postgresql.cnpg.io" to a TS identifier.
const crdNameToIdentifier = (crdName: string): string => {
	// Take the first part (the plural resource name), then PascalCase it.
	const resource = crdName.split(".")[0] ?? crdName;
	return resource
		.split(/[-_]/)
		.map((s) => `${s.charAt(0).toUpperCase()}${s.slice(1)}`)
		.join("");
};

// Generate the TypeScript source for one CRD.
const generateCrdTs = async (crd: CrdDocument): Promise<string> => {
	const identifier = crdNameToIdentifier(crd.crdName);
	const inputType = `${identifier}Input`;

	// json-schema-to-typescript compile — generates the TS interface for the CRD spec.
	let compiledTypes: string;
	try {
		compiledTypes = await compile(crd.schema as Parameters<typeof compile>[0], inputType, {
			bannerComment: "",
			additionalProperties: false,
			enableConstEnums: false,
			strictIndexSignatures: false,
		});
	} catch {
		// Fallback for schemas that json-schema-to-typescript can't handle
		compiledTypes = `export type ${inputType} = Record<string, unknown>;\n`;
	}

	// Manifest constructor alongside the type
	const parts = [
		compiledTypes,
		`// CRD: ${crd.crdName} (group: ${crd.group}, versions: ${crd.versions.join(", ")})`,
		`// Use Manifest.make from @konfig.ts/core to produce a RawYaml resource at render time.`,
	];

	return parts.join("\n");
};

// Pull chart and return the .tgz path (cached).
const pullChart = async (opts: CrdExtractOptions): Promise<string> => {
	await fs.mkdir(opts.cacheDir, { recursive: true });
	const cachedTgz = path.join(opts.cacheDir, `${opts.chart}-${opts.version}.tgz`);

	const exists = await fs
		.access(cachedTgz)
		.then(() => true)
		.catch(() => false);

	if (!exists) {
		await exec(
			[
				"helm",
				"pull",
				"--repo",
				opts.repo,
				opts.chart,
				"--version",
				opts.version,
				"--destination",
				opts.cacheDir,
			].join(" "),
		);
	}
	return cachedTgz;
};

/**
 * Extract CRD types from a Helm chart (T6.3 implementation).
 *
 * 1. Pull chart to cache.
 * 2. Pull chart with --untar to a temp dir to read crds/*.yaml.
 * 3. Also run `helm template --include-crds` to catch any CRDs that ship
 *    only in the chart templates.
 * 4. Dedupe by metadata.name.
 * 5. Parse schemas and generate TS interfaces.
 * 6. Write to <outDir>/<id>.ts with the generated header.
 */
export const extractCrds = async (opts: CrdExtractOptions): Promise<void> => {
	const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "tsk-crd-"));
	try {
		// Pull with --untar for crds/ directory access
		await exec(
			[
				"helm",
				"pull",
				"--repo",
				opts.repo,
				opts.chart,
				"--version",
				opts.version,
				"--untar",
				"--destination",
				tmpDir,
			].join(" "),
		);

		const chartDir = path.join(tmpDir, opts.chart);
		const crdsDir = path.join(chartDir, "crds");

		const allYaml: string[] = [];

		// Read crds/*.yaml
		const crdsExists = await fs
			.access(crdsDir)
			.then(() => true)
			.catch(() => false);
		if (crdsExists) {
			const crdFiles = await fs.readdir(crdsDir);
			for (const f of crdFiles.filter((n) => n.endsWith(".yaml") || n.endsWith(".yml"))) {
				const content = await fs.readFile(path.join(crdsDir, f), "utf8");
				allYaml.push(content);
			}
		}

		// helm template --include-crds
		const cachedTgz = await pullChart(opts);
		const { stdout: templateOut } = await exec(
			["helm", "template", opts.chart, cachedTgz, "--include-crds", "--no-hooks"].join(" "),
		);
		allYaml.push(templateOut);

		// Parse + dedupe
		const seen = new Map<string, CrdDocument>();
		for (const yaml of allYaml) {
			for (const crd of parseCrdDocs(yaml)) {
				if (!seen.has(crd.crdName)) seen.set(crd.crdName, crd);
			}
		}

		if (seen.size === 0) {
			// No CRDs found — write an empty stub file
			await fs.mkdir(opts.outDir, { recursive: true });
			const stubPath = path.join(opts.outDir, `${opts.id}.ts`);
			await fs.writeFile(
				stubPath,
				`${GENERATED_HEADER}\n// No CRDs found in chart ${opts.chart}@${opts.version}\nexport {};\n`,
				"utf8",
			);
			return;
		}

		// Generate TS for each CRD
		const parts: string[] = [GENERATED_HEADER, ""];
		for (const crd of seen.values()) {
			const ts = await generateCrdTs(crd);
			parts.push(ts, "");
		}

		await fs.mkdir(opts.outDir, { recursive: true });
		const outPath = path.join(opts.outDir, `${opts.id}.ts`);
		await fs.writeFile(outPath, parts.join("\n"), "utf8");
	} finally {
		await fs.rm(tmpDir, { recursive: true, force: true });
	}
};

/**
 * Re-extract CRDs to a temp dir and compare byte-for-byte against committed
 * files (T6.5). Returns a list of files that have drifted.
 */
export const verifyCrds = async (
	releases: readonly CrdExtractOptions[],
	committedDir: string,
): Promise<string[]> => {
	const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "tsk-verify-"));
	const drifted: string[] = [];
	try {
		for (const release of releases) {
			await extractCrds({ ...release, outDir: tmpDir });
			const tmpFile = path.join(tmpDir, `${release.id}.ts`);
			const committedFile = path.join(committedDir, `${release.id}.ts`);

			const [tmpContent, committedContent] = await Promise.all([
				fs.readFile(tmpFile, "utf8").catch(() => ""),
				fs.readFile(committedFile, "utf8").catch(() => ""),
			]);

			// Check header is present in committed
			if (!committedContent.startsWith(GENERATED_HEADER)) {
				drifted.push(`${release.id}.ts (missing generated header)`);
				continue;
			}

			if (tmpContent !== committedContent) {
				drifted.push(`${release.id}.ts`);
			}
		}
	} finally {
		await fs.rm(tmpDir, { recursive: true, force: true });
	}
	return drifted;
};
