
import { exec as execCb } from "node:child_process";
import * as fs from "node:fs/promises";
import * as os from "node:os";
import * as path from "node:path";
import { promisify } from "node:util";
import { coerce } from "@konfig.ts/core";
import { compile } from "json-schema-to-typescript";
import * as YAML from "yaml";

const exec = promisify(execCb);

export const GENERATED_HEADER = "// Generated by @konfig.ts/cli — do not edit by hand";

export interface CrdExtractOptions {
	readonly repo: string;
	readonly chart: string;
	readonly version: string;
	readonly id: string;
	readonly outDir: string;
	readonly cacheDir: string;
}

interface CrdDocument {
	readonly crdName: string;
	readonly group: string;
	readonly schema: Record<string, unknown>;
	readonly versions: readonly string[];
}

const _parseCrdDocs = (yamlText: string): CrdDocument[] => {
	const docs: unknown[] = [];
	for (const chunk of yamlText.split(/^---\s*$/m)) {
		const trimmed = chunk.trim();
		if (!trimmed) continue;
		try {
			const parsed = YAML.parse(trimmed);
			if (parsed && typeof parsed === "object") docs.push(parsed);
		} catch {
			// Skip unparseable chunks
		}
	}

	const crds: CrdDocument[] = [];
	for (const doc of docs) {
		const d = coerce<Record<string, unknown>>(doc);
		if (d.kind !== "CustomResourceDefinition") continue;
		const meta = coerce<Record<string, unknown> | undefined>(d.metadata);
		const spec = coerce<Record<string, unknown> | undefined>(d.spec);
		if (!meta || !spec) continue;

		const crdName = String(meta.name ?? "");
		if (!crdName) continue;

		const group = String(spec.group ?? "");
		const versions = coerce<Array<Record<string, unknown>> | undefined>(spec.versions);
		if (!versions?.length) continue;

		const versionNames: string[] = [];
		let schema: Record<string, unknown> | undefined;

		for (const v of versions) {
			const vName = String(v.name ?? "");
			if (vName) versionNames.push(vName);
			if (!schema) {
				const validation = coerce<Record<string, unknown> | undefined>(v.schema);
				const openAPI = coerce<Record<string, unknown> | undefined>(validation?.openAPIV3Schema);
				if (openAPI) schema = openAPI;
			}
		}

		if (!schema) {
			schema = { type: "object", additionalProperties: true };
		}

		crds.push({ crdName, group, schema, versions: versionNames });
	}
	return crds;
};

const _crdNameToIdentifier = (crdName: string): string => {
	const resource = crdName.split(".")[0] ?? crdName;
	return resource
		.split(/[-_]/)
		.map((s) => `${s.charAt(0).toUpperCase()}${s.slice(1)}`)
		.join("");
};

const _generateCrdTs = async (crd: CrdDocument): Promise<string> => {
	const identifier = _crdNameToIdentifier(crd.crdName);
	const inputType = `${identifier}Input`;

	let compiledTypes: string;
	try {
		compiledTypes = await compile(coerce<Parameters<typeof compile>[0]>(crd.schema), inputType, {
			bannerComment: "",
			additionalProperties: false,
			enableConstEnums: false,
			strictIndexSignatures: false,
		});
	} catch {
		compiledTypes = `export type ${inputType} = Record<string, unknown>;\n`;
	}

	const parts = [
		compiledTypes,
		`// CRD: ${crd.crdName} (group: ${crd.group}, versions: ${crd.versions.join(", ")})`,
		`// Use Manifest.make from @konfig.ts/core to produce a RawYaml resource at render time.`,
	];

	return parts.join("\n");
};

const _pullChart = async (opts: CrdExtractOptions): Promise<string> => {
	await fs.mkdir(opts.cacheDir, { recursive: true });
	const cachedTgz = path.join(opts.cacheDir, `${opts.chart}-${opts.version}.tgz`);

	const exists = await fs
		.access(cachedTgz)
		.then(() => true)
		.catch(() => false);

	if (!exists) {
		await exec(
			[
				"helm",
				"pull",
				"--repo",
				opts.repo,
				opts.chart,
				"--version",
				opts.version,
				"--destination",
				opts.cacheDir,
			].join(" "),
		);
	}
	return cachedTgz;
};

export const extractCrds = async (opts: CrdExtractOptions): Promise<void> => {
	const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "tsk-crd-"));
	try {
		await exec(
			[
				"helm",
				"pull",
				"--repo",
				opts.repo,
				opts.chart,
				"--version",
				opts.version,
				"--untar",
				"--destination",
				tmpDir,
			].join(" "),
		);

		const chartDir = path.join(tmpDir, opts.chart);
		const crdsDir = path.join(chartDir, "crds");

		const allYaml: string[] = [];

		const crdsExists = await fs
			.access(crdsDir)
			.then(() => true)
			.catch(() => false);
		if (crdsExists) {
			const crdFiles = await fs.readdir(crdsDir);
			for (const f of crdFiles.filter((n) => n.endsWith(".yaml") || n.endsWith(".yml"))) {
				const content = await fs.readFile(path.join(crdsDir, f), "utf8");
				allYaml.push(content);
			}
		}

		const cachedTgz = await _pullChart(opts);
		const { stdout: templateOut } = await exec(
			["helm", "template", opts.chart, cachedTgz, "--include-crds", "--no-hooks"].join(" "),
		);
		allYaml.push(templateOut);

		const seen = new Map<string, CrdDocument>();
		for (const yaml of allYaml) {
			for (const crd of _parseCrdDocs(yaml)) {
				if (!seen.has(crd.crdName)) seen.set(crd.crdName, crd);
			}
		}

		if (seen.size === 0) {
			await fs.mkdir(opts.outDir, { recursive: true });
			const stubPath = path.join(opts.outDir, `${opts.id}.ts`);
			await fs.writeFile(
				stubPath,
				`${GENERATED_HEADER}\n// No CRDs found in chart ${opts.chart}@${opts.version}\nexport {};\n`,
				"utf8",
			);
			return;
		}

		const parts: string[] = [GENERATED_HEADER, ""];
		for (const crd of seen.values()) {
			const ts = await _generateCrdTs(crd);
			parts.push(ts, "");
		}

		await fs.mkdir(opts.outDir, { recursive: true });
		const outPath = path.join(opts.outDir, `${opts.id}.ts`);
		await fs.writeFile(outPath, parts.join("\n"), "utf8");
	} finally {
		await fs.rm(tmpDir, { recursive: true, force: true });
	}
};

export interface VerifyCrdsInput {
	readonly releases: readonly CrdExtractOptions[];
	readonly committedDir: string;
}
export const verifyCrds = async (input: VerifyCrdsInput): Promise<string[]> => {
	const { releases, committedDir } = input;
	const tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), "tsk-verify-"));
	const drifted: string[] = [];
	try {
		for (const release of releases) {
			await extractCrds({ ...release, outDir: tmpDir });
			const tmpFile = path.join(tmpDir, `${release.id}.ts`);
			const committedFile = path.join(committedDir, `${release.id}.ts`);

			const [tmpContent, committedContent] = await Promise.all([
				fs.readFile(tmpFile, "utf8").catch(() => ""),
				fs.readFile(committedFile, "utf8").catch(() => ""),
			]);

			if (!committedContent.startsWith(GENERATED_HEADER)) {
				drifted.push(`${release.id}.ts (missing generated header)`);
				continue;
			}

			if (tmpContent !== committedContent) {
				drifted.push(`${release.id}.ts`);
			}
		}
	} finally {
		await fs.rm(tmpDir, { recursive: true, force: true });
	}
	return drifted;
};
