apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: ghcr-pull
    namespace: app
spec:
    secretTemplates:
        - name: ghcr-pull
          type: kubernetes.io/dockerconfigjson
          stringData:
              .dockerconfigjson: ENC[AES256_GCM,data:ZmFrZS1lbmNyeXB0ZWQtZG9ja2VyY29uZmlnLWRlbW8K,iv:0000000000000000000000000000000000000000000000000000000000000000,tag:00000000000000000000000000000000,type:str]
sops:
    age:
        - recipient: age1demo000000000000000000000000000000000000000000000000000example
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-31T00:00:00Z"
    mac: ENC[AES256_GCM,data:demo,iv:demo,tag:demo,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
