apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: db-creds
    namespace: app
spec:
    secretTemplates:
        - name: db-creds
          type: Opaque
          stringData:
              url: ENC[AES256_GCM,data:ZmFrZS1lbmNyeXB0ZWQtdXJsLWRlbW8K,iv:0000,tag:0000,type:str]
              username: ENC[AES256_GCM,data:ZmFrZQ==,iv:0000,tag:0000,type:str]
              password: ENC[AES256_GCM,data:ZmFrZQ==,iv:0000,tag:0000,type:str]
sops:
    age:
        - recipient: age1demo000000000000000000000000000000000000000000000000000example
          enc: |
              -----BEGIN AGE ENCRYPTED FILE-----
              -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-31T00:00:00Z"
    mac: ENC[AES256_GCM,data:demo,iv:demo,tag:demo,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
